name: Arduino Pro IDE

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *' # run every day at 3AM (https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)

jobs:

  build:
    strategy:
      matrix:
        config:
          - os: windows-2016
          - os: ubuntu-latest
          - os: macos-latest
          # - os: rsora-rpi-arm # self-hosted armhf
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 90
    env:
      CERTIFICATE_PATH: /tmp/macos_signing_certificate.p12

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Generate signing certificate file [macOS]
        if: runner.OS == 'macOS'
        run: |
            # APPLE_SIGNING_CERTIFICATE_P12 secret was produced by following the procedure from:
            # https://www.kencochrane.com/2020/08/01/build-and-sign-golang-binaries-for-macos-with-github-actions/#exporting-the-developer-certificate
            echo "${{ secrets.APPLE_SIGNING_CERTIFICATE_P12 }}" | base64 --decode > "${{ env.CERTIFICATE_PATH }}"

      - name: Package
        shell: bash
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          IS_NIGHTLY: ${{ github.event_name == 'schedule' }}
          IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
            # electron-builder will try to sign during the Windows job if these environment variables are defined
            if [ "${{ runner.OS }}" = "macOS" ]; then
              # See: https://www.electron.build/code-signing
              export CSC_LINK="${{ env.CERTIFICATE_PATH }}"
              export CSC_KEY_PASSWORD="${{ secrets.KEYCHAIN_PASSWORD }}"
            fi
            yarn --cwd ./electron/packager/
            yarn --cwd ./electron/packager/ package

      - name: Upload [GitHub Actions]
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: electron/build/dist/build-artifacts/

  publish:
    needs: build
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Download [GitHub Actions]
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build-artifacts

      - name: Publish Nightly [S3]
        uses: kittaakos/upload-s3-action@v0.0.1
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.DOWNLOADS_BUCKET }}
          source_dir: build-artifacts/
          destination_dir: arduino-pro-ide/nightly/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download [GitHub Actions]
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build-artifacts

      - name: Create Release [GitHub]
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Publish Release [GitHub]
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build-artifacts/*
          tag: ${{ github.ref }}
          file_glob: true

      - name: Publish Release [S3]
        uses: kittaakos/upload-s3-action@v0.0.1
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.DOWNLOADS_BUCKET }}
          source_dir: build-artifacts/
          destination_dir: arduino-pro-ide/
