storage: ./storage
uplinks:
  npmjs:
    url: 'https://registry.npmjs.org/'
packages:
  '**':
    access: $all
    publish: $anonymous
    unpublish: $anonymous
    proxy: npmjs
server:
  keepAliveTimeout: 60
listen:
  - 'localhost:4873'
max_body_size: 100mb
log:
  type: stdout
  format: pretty
  level: warn
